### PR TITLE
RFC: Add tasks to SHELL_PLUS_IMPORTS

### PR DESCRIPTION
**Pull request by zachmullen**
I've added this configuration on multiple Resonant projects now. Wondering if others will find this useful too.

### CODE REVIEW

**Comment by zachmullen** [comment]
I realize it may also make sense to move this out of `DevelopmentConfiguration` and into the app mixin, as people sometimes use `shell_plus` in production.

**Review by brianhelba — APPROVED** [review]
LGTM, good improvement. Thanks.

**Comment by brianhelba** [comment]
After discussing with @danlamanna, we realized that `django-extensions` should probably be setup as a development-only dependency, since we just don't trust it enough to depend on it for production use. Of course, downstream developers can change this at their own risk.

@danlamanna is going to make the changes to make `django-extensions` dev-only more generally.

**Comment by zachmullen** [comment]
I occasionally run `heroku exec ./manage.py shell_plus`, but if this is a security concern, I could live without that ability.

**Pull request merged**
